version: "3.9"
services:
  posting:
    build:
      context: ./PostingService
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:5000
    networks:
      - internal
    environment:
      CONNECTION_STRING: Host=posting-db;User=root;Password=root;Port=5432

  posting-db:
    image: postgres
    restart: always
    volumes: 
      - posting-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: posting
    ports:
      - 5432:5432
    networks:
      - internal

  servicebus:
    image: rabbitmq
    restart: always
    ports:
      - 5672:5672
    volumes:
      - servicebus-data:/var/lib/rabbitmq

volumes:
  posting-data:
  servicebus-data:

networks:
  internal:
