version: "3.9"
services:
  posting:
    build:
      context: ./PostingService
      dockerfile: Dockerfile
    restart: always
    depends_on: 
      - servicebus
    networks:
      - internal
    environment:
      CONNECTION_STRING: Host=posting-db;User=root;Password=root;Port=5432
      SERVICE_BUS_ADDRESS: servicebus
    volumes:
      - ./NugetPackages:/NugetPackages

  gateway:
    build:
      context: ./W4SGateway
      dockerfile: Dockerfile
    restart: always
    depends_on: 
      - servicebus
    ports:
      - 80:5000
    networks:
      - internal
    environment:
      SERVICE_BUS_ADDRESS: servicebus
    volumes:
      - ./NugetPackages:/NugetPackages

  posting-db:
    image: postgres
    restart: always
    volumes: 
      - posting-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: posting
    ports:
      - 5432:5432
    networks:
      - internal

  servicebus:
    build: ./RabbitMq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - servicebus-data:/var/lib/rabbitmq
    networks:
      - internal

volumes:
  posting-data:
  servicebus-data:

networks:
  internal:
