version: "3.9"
services:

  posting:
    build:
      context: ./W4S.PostingService
      dockerfile: Dockerfile
      args:
        MODE: Debug
    restart: always
    depends_on: 
      - servicebus
    networks:
      - internal
    environment:
      CONNECTION_STRING: Database=offers;Host=db;Username=root;Password=root;Port=5432
      BUS_BROKER_ADDRESS: servicebus
      SERVICE_NAME: Posting

  db:
    image: postgres
    restart: always
    volumes: 
      - db-data:/var/lib/postgresql/data
      - ./Postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - internal

  gateway:
    build:
      context: ./W4S.Gateway
      dockerfile: Dockerfile
      args:
        MODE: Debug
    restart: always
    depends_on: 
      - servicebus
    ports:
      - 80:5000
    networks:
      - internal
    environment:
      BUS_BROKER_ADDRESS: servicebus
      SERVICE_NAME: Gateway

  servicebus:
    build: ./RabbitMq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - servicebus-data:/var/lib/rabbitmq
    networks:
      - internal

  registration:
    build:
      context: ./W4S.RegistrationMicroservice
      dockerfile: Dockerfile
      args:
        MODE: Debug
    restart: always
    depends_on: 
      - servicebus
    networks:
      - internal
    environment:
      CONNECTION_STRING: Database=users;Host=db;Username=root;Password=root;Port=5432
      BUS_BROKER_ADDRESS: servicebus
      SERVICE_NAME: Registration

volumes:
  db-data:
  servicebus-data:

networks:
  internal:
