version: "3.9"
services:

  posting:
    build:
      context: ./W4S.PostingService
      dockerfile: Dockerfile
      args:
        MODE: Debug
    restart: always
    depends_on: 
      - servicebus
    networks:
      - internal
    environment:
      CONNECTION_STRING: Host=posting-db;User=root;Password=root;Port=5432
      BUS_BROKER_ADDRESS: servicebus
      SERVICE_NAME: Posting

  posting-db:
    image: postgres
    restart: always
    volumes: 
      - posting-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: posting
    networks:
      - internal

  gateway:
    build:
      context: ./W4S.Gateway
      dockerfile: Dockerfile
      args:
        MODE: Debug
    restart: always
    depends_on: 
      - servicebus
    ports:
      - 80:5000
    networks:
      - internal
    environment:
      BUS_BROKER_ADDRESS: servicebus
      SERVICE_NAME: Gateway

  servicebus:
    build: ./RabbitMq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - servicebus-data:/var/lib/rabbitmq
    networks:
      - internal

  registration-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Kutafon2137
    volumes:
      - registration-data:/var/opt/mssql

  registration:
    build:
      context: ./W4S.RegistrationMicroservice
      dockerfile: Dockerfile
      args:
        MODE: Debug
    restart: always
    depends_on: 
      - servicebus
    networks:
      - internal
    environment:
      CONNECTION_STRING: Server=registration-db-1;Database=W4SRegistrationUserbase;User=sa;Password=Kutafon2137;Trusted_Connection=True;encrypt=false
      BUS_BROKER_ADDRESS: servicebus
      SERVICE_NAME: Registration

volumes:
  posting-data:
  servicebus-data:
  registration-data:

networks:
  internal:
